# Generated by Django 3.0.5 on 2020-07-17 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='image_extract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_no', models.IntegerField(unique=True)),
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=250, null=True)),
                ('mother_name', models.CharField(max_length=250, null=True)),
                ('college_name', models.CharField(max_length=250, null=True)),
                ('center_no', models.IntegerField(null=True)),
                ('total_marks', models.IntegerField(null=True)),
            ],
        ),
    ]
